image: Visual Studio 2017
environment:
  DOTNET_CLI_TELEMETRY_OPTOUT: true
  DOTNET_SKIP_FIRST_TIME_EXPERIENCE: true
build:
    project: src/AwesomeCMSCore/AwesomeCMSCore.sln
before_build:
  - cd src/AwesomeCMSCore 
  - dotnet restore
  - dotnet build